cols_display_config_sorted = [
    ("VXDCollection", 0, 5, 1),
    ("SITCollection", 0, 5, 1),
    ("FTD_PIXELCollection", 0, 5, 1),
    ("FTD_STRIPCollection", 0, 5, 1),
    ("FTDCollection", 0, 5, 1),
    ("TPCCollection", 0, 3, 1),
    ("SETCollection", 0, 3, 1),
    ("ETDCollection", 0, 3, 1),
    ("VertexBarrelCollection", 0, 5, 1),
    ("VertexEndcapCollection", 0, 5, 1),
    ("InnerTrackerBarrelCollection", 0, 5, 1),
    ("InnerTrackerEndcapCollection", 0, 5, 1),
    ("OuterTrackerBarrelCollection", 0, 5, 1),
    ("OuterTrackerEndcapCollection", 0, 5, 1),
    ("VXDTrackerHits", 0, 5, 11),
    ("SITTrackerHits", 0, 5, 11),
    ("TPCTrackerHits", 0, 5, 11),
    ("FTDTrackerHits", 0, 5, 11),
    ("FTDStripTrackerHits", 0, 5, 11),
    ("FTDPixelTrackerHits", 0, 5, 11),
    ("FTDSpacePoints", 0, 5, 11),
    ("SETTrackerHits", 0, 5, 11),
    ("ITrackerEndcapHits", 0, 5, 11),
    ("ITrackerHits", 0, 5, 11),
    ("OTrackerEndcapHits", 0, 5, 11),
    ("OTrackerHits", 0, 5, 11),
    ("VXDEndcapTrackerHits", 0, 5, 11),
    ("TruthTracks", 0, 6, 3),
    ("ForwardTracks", 0, 6, 4),
    ("SiTracks", 0, 6, 5),
    ("ClupatraTracks", 0, 6, 6),
    ("MarlinTrkTracks", 0, 6, 7),
    ("MCParticle", 0, 3, 0),
    ("VertexBarrelHits", 0, 5, 11),
    ("VertexEndcapHits", 0, 5, 11),
    ("InnerTrackerBarrelHits", 0, 5, 11),
    ("InnerTrackerEndcapHits", 0, 5, 11),
    ("OuterTrackerBarrelHits", 0, 5, 11),
    ("OuterTrackerEndcapHits", 0, 5, 11),
    ("Tracks", 0, 3, 3),
]

config = {
    "ColorByEnergy": ["false"],
    "ColorByEnergyAutoColor": ["false"],
    "ColorByEnergyBrightness": ["1.0"],
    "ColorByEnergyMax": ["35.0"],
    "ColorByEnergyMin": ["0.0"],
    "ColorByEnergySaturation": ["1.0"],
    "ColorScheme": ["10"],
    "DetailledDrawing": ["VXD", "VertexBarrel"],
    "DrawDetector": ["true"],
    "DrawDetectorID": ["0"],
    "DrawHelixForPFOs": ["0"],
    "DrawHelixForTrack": ["0"],
    "DrawInLayer": [str(item) for col_config in cols_display_config_sorted for item in col_config],
    "DrawSurfaces": ["true"],
    "HelixMaxR": ["2000"],
    "HelixMaxZ": ["2500"],
    "MCParticleEnergyCut": ["0.001"],
    "ScaleLineThickness": ["1"],
    "ScaleMarkerSize": ["1"],
    "UseColorForHelixTracks": ["0"],
    "UseTPCForLimitsOfHelix": ["true"],
    "UsingParticleGun": ["false"],
    "WaitForKeyboard": ["1"],
}
